### ISSUE TITLE
crash in aggregator when nonexistent query handler is invoked

### ISSUE THREAD

**Issue by sboyettedh** [sboyettedh/whiplash#12]
Meant to call 'echo' but called 'ping' and this happened

```
sboyette@peon7808:~$ panic: runtime error: index out of range

goroutine 23 [running]:
main.echoQHandler(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/sboyette/src/github.com/sboyettedh/whiplash/cmd/whiplash-aggregator/queryhandlers.go:13 +0x57a
firepear.net/asock.(*Asock).reqDispatch(0xc82008e420, 0x7f4ae54bb000, 0xc820080038, 0x2, 0x1, 0xc82000a950, 0x4, 0x8, 0x0, 0x0, ...)
    /Users/sboyette/src/firepear.net/asock/net.go:191 +0x84a
firepear.net/asock.(*Asock).connHandler(0xc82008e420, 0x7f4ae54bb000, 0xc820080038, 0x2)
    /Users/sboyette/src/firepear.net/asock/net.go:82 +0x48d
created by firepear.net/asock.(*Asock).sockAccept
    /Users/sboyette/src/firepear.net/asock/net.go:48 +0x278
```

Asock err handling should have caught that.

**Comment by sboyettedh** [comment]
Crash isn't in asock. That's just what's waiting on the other end. Crash is in the aggregator stitching together the QueryResponse when there is no subcommand passed in.

This will be handled client side by Jira ticket 1259, but should be guarded on the aggregator side as well.

**Comment by sboyettedh** [comment]
Fixed with query handler helper funcs. See qhEcho for how to write a conformant query handler.
